language: go
go:
  - 1.10.x

install:
  - go get -u gopkg.in/alecthomas/gometalinter.v2 && gometalinter.v2 --install

script:
  - ./script/test_version.sh
  - gometalinter.v2 --config .linter.json ./...
  - go test -race ./...
  - ./script/codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
